"""initial-migration

Revision ID: 17a2585c9926
Revises: 
Create Date: 2023-03-20 15:49:40.215704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a2585c9926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('admin_type', sa.String(length=100), nullable=True),
    sa.Column('registered_by', sa.String(length=30), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('registered_by', sa.String(length=30), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ctaegory_description', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serving_time', sa.String(length=50), nullable=True),
    sa.Column('meal_description', sa.String(length=200), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('opening_hrs', sa.String(length=6), nullable=True),
    sa.Column('closing_hrs', sa.String(length=6), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('district_code', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('made_by', sa.Integer(), nullable=True),
    sa.Column('local_address', sa.String(length=200), nullable=True),
    sa.Column('menu_item', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('made_at', sa.DateTime(), nullable=True),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['made_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_item'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('reg_at', sa.DateTime(), nullable=True),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divisions')
    op.drop_table('order')
    op.drop_table('districts')
    op.drop_table('settings')
    op.drop_table('regions')
    op.drop_table('menu')
    op.drop_table('meals')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
